In [1]:
import pandas as pd
import numpy as np

In [25]:
file_name ="fewers_20250202-211640.csv"
df_raw =pd.read_csv(f"/app/yolo_structure/results/{file_name}")
# df_raw["datetime"] = pd.to_datetime(df_raw["datetime"], format="%Y%m%d-%H%M%S.%f")
df_raw .tail(5)

,datetime,distance,event,detected,source_name,frame_hash,frame_num
968,20250202-211712,0,REVERSE,car,fewers.mp4,fewers_REVERSE_3,568
969,20250202-211712,0,REVERSE,car,fewers.mp4,fewers_REVERSE_3,569
970,20250202-211712,0,STOP,car,fewers.mp4,fewers_STOP_2,570
971,20250202-211712,0,STOP,car,fewers.mp4,fewers_STOP_1,571
972,20250202-211712,0,STOP,car,fewers.mp4,fewers_STOP_2,571

In [26]:
# frame_hash별로 그룹핑하고, 1초 이내 5개 이상 존재하는 경우 찾기
df_raw_person = df_raw[df_raw["detected"] == "person"]
df_raw_person

# frame_hash별로 그룹화 후 frame_num 연속성 확인
df_filtered_person = pd.DataFrame()

grouped = df_raw_person.groupby("frame_hash")
for _, group in grouped:
    group = group.sort_values(by="frame_num").reset_index(drop=True)
    group["diff"] = group["frame_num"].diff().fillna(1)
    group["consec_group"] = (group["diff"] != 1).cumsum()
    valid_groups = group.groupby("consec_group").filter(lambda x: len(x) >= 5)
    df_filtered_person = pd.concat([df_filtered_person, valid_groups.drop(columns=["diff", "consec_group"])])

# 결과 출력
df_filtered_person

,datetime,distance,event,detected,source_name,frame_hash,frame_num
5,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_3,203
6,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_3,204
7,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_3,205
8,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_3,206
9,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_3,207
...,...,...,...,...,...,...,...
57,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_5,200
58,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_5,201
59,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_5,202
60,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_5,203
61,20250202-211705,0,PERSON,person,fewers.mp4,fewers_PERSON_5,204

In [27]:
# frame_hash별로 그룹핑하고, 1초 이내 5개 이상 존재하는 경우 찾기
df_raw_stop = df_raw[df_raw["event"] == "STOP"]
df_raw_stop

# frame_hash별로 그룹화 후 frame_num 연속성 확인
df_filtered_stop = pd.DataFrame()

grouped = df_raw_stop.groupby("frame_hash")
for _, group in grouped:
    group = group.sort_values(by="frame_num").reset_index(drop=True)
    group["diff"] = group["frame_num"].diff().fillna(1)
    group["consec_group"] = (group["diff"] != 1).cumsum()
    valid_groups = group.groupby("consec_group").filter(lambda x: len(x) >= 5)
    df_filtered_stop = pd.concat([df_filtered_stop, valid_groups.drop(columns=["diff", "consec_group"])])

# 결과 출력
df_filtered_stop

,datetime,distance,event,detected,source_name,frame_hash,frame_num
3,20250202-211644,0,STOP,car,fewers.mp4,fewers_STOP_1,7
4,20250202-211645,0,STOP,car,fewers.mp4,fewers_STOP_1,8
5,20250202-211647,0,STOP,car,fewers.mp4,fewers_STOP_1,9
6,20250202-211649,0,STOP,car,fewers.mp4,fewers_STOP_1,10
7,20250202-211651,0,STOP,car,fewers.mp4,fewers_STOP_1,11
...,...,...,...,...,...,...,...
63,20250202-211712,0,STOP,car,fewers.mp4,fewers_STOP_3,558
64,20250202-211712,0,STOP,car,fewers.mp4,fewers_STOP_3,559
65,20250202-211712,0,STOP,car,fewers.mp4,fewers_STOP_3,560
66,20250202-211712,0,STOP,car,fewers.mp4,fewers_STOP_3,561
67,20250202-211712,0,STOP,car,fewers.mp4,fewers_STOP_3,562

In [28]:
# frame_hash별로 그룹핑하고, 1초 이내 5개 이상 존재하는 경우 찾기
df_raw_reverse = df_raw[df_raw["event"] == "REVERSE"]
df_raw_reverse

# frame_hash별로 그룹화 후 frame_num 연속성 확인
df_filtered_reverse = pd.DataFrame()

grouped = df_raw_reverse.groupby("frame_hash")
for _, group in grouped:
    group = group.sort_values(by="frame_num").reset_index(drop=True)
    group["diff"] = group["frame_num"].diff().fillna(1)
    group["consec_group"] = (group["diff"] != 1).cumsum()
    valid_groups = group.groupby("consec_group").filter(lambda x: len(x) >= 3)
    df_filtered_reverse = pd.concat([df_filtered_reverse, valid_groups.drop(columns=["diff", "consec_group"])])

# 결과 출력
df_filtered_reverse

,datetime,distance,event,detected,source_name,frame_hash,frame_num
41,20250202-211708,0,REVERSE,car,fewers.mp4,fewers_REVERSE_3,352
42,20250202-211708,0,REVERSE,car,fewers.mp4,fewers_REVERSE_3,353
43,20250202-211708,0,REVERSE,car,fewers.mp4,fewers_REVERSE_3,354
44,20250202-211708,0,REVERSE,car,fewers.mp4,fewers_REVERSE_3,355
60,20250202-211709,0,REVERSE,car,fewers.mp4,fewers_REVERSE_3,416
61,20250202-211709,0,REVERSE,car,fewers.mp4,fewers_REVERSE_3,417
62,20250202-211709,0,REVERSE,car,fewers.mp4,fewers_REVERSE_3,418

In [29]:
import ollama
import os
import cv2

origin_dir = "/app"
## 최종 저장경로 설정!!
results_dir = os.path.join(origin_dir,"yolo_structure","results")
## 사건파일저장
crop_save_dir = os.path.join(results_dir,"frame_img")

In [ ]:
llm_res_l = []
for index,value in df_filtered_stop.iterrows():
    if value["detected"] !="car":
        llm_res_l.append(value["detected"])
        continue
   
    crop_filename = os.path.join(crop_save_dir,value["frame_hash"]+"_"+ str(value["frame_num"]) +".jpg")
    res = ollama.chat(
        model= "llama3.2-vision:11b",
        messages=[
            {
                'role': 'user',
                'content': "tell me what is in this image. Answer only one in [SEDAN/SUV/VAN/TRUCK/BUS] answer in one word",
                'images': [crop_filename]
            }
        ]
    )
    
    print(res['message']['content'])

    final_result = res['message']['content'].upper().replace(".","").replace(" ","")
    print(f"{crop_filename} / Ollama Result: {final_result}")
    llm_res_l.append(final_result)
df_filtered_stop["llm_res"] = llm_res_l
df_filtered_stop

Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_7.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_8.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_9.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_10.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_11.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_12.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_13.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_36.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_37.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_38.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_39.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_40.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_41.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_42.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_47.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_48.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_49.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_50.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_51.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_52.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_53.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_54.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_55.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_56.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_58.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_59.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_60.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_61.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_62.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_63.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_64.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_65.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_66.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_70.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_71.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_72.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_73.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_74.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_75.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_90.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_91.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_92.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_93.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_94.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_95.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_115.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_116.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_117.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_118.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_119.jpg / Ollama Result: SEDAN
VAN.
/app/yolo_structure/results/frame_img/fewers_STOP_1_120.jpg / Ollama Result: VAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_121.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_122.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_193.jpg / Ollama Result: SEDAN
car.
/app/yolo_structure/results/frame_img/fewers_STOP_1_194.jpg / Ollama Result: CAR
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_195.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_196.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_197.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_198.jpg / Ollama Result: SEDAN
Sedan.
/app/yolo_structure/results/frame_img/fewers_STOP_1_199.jpg / Ollama Result: SEDAN

In [ ]:
llm_res_l = []
for index,value in df_filtered_reverse.iterrows():
    if value["detected"] !="car":
        llm_res_l.append(value["detected"])
        continue
   
    crop_filename = os.path.join(crop_save_dir,value["frame_hash"]+"_"+ str(value["frame_num"]) +".jpg")
    res = ollama.chat(
        model= "llama3.2-vision:11b",
        messages=[
            {
                'role': 'user',
                'content': "tell me what is in this image. Answer only one in [SEDAN/SUV/VAN/TRUCK/BUS] answer in one word",
                'images': [crop_filename]
            }
        ]
    )
    
    print(res['message']['content'])

    final_result = res['message']['content'].upper().replace(".","").replace(" ","")
    print(f"{crop_filename} / Ollama Result: {final_result}")
    llm_res_l.append(final_result)
df_filtered_reverse["llm_res"] = llm_res_l
df_filtered_reverse